runtime: python27
api_version: 1
threadsafe: true

# default_expiration: "30d"

handlers:
- url: .*
  script: main.app
  secure: always

libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$
- ^\.git$
- ^\.ropeproject$
- ^node_modules$
